### ISSUE TITLE
Local stoage

### ISSUE THREAD

**Issue by rmwillow** [rmwillow/citizenGuard#28]
Store address from input
[address: 1231 loe lane, 78759]

**Comment by john-tech30** [comment]
if (localStorage.clickcount) {
  localStorage.clickcount = Number(localStorage.clickcount) + 1;
} else {
  localStorage.clickcount = 1;
}
document.getElementById("result").innerHTML = "You have clicked the button " +
localStorage.clickcount + " time(s).";

**Comment by rmwillow** [comment]
Try this 

// Store
let searchedLoc = [];
searchedLoc.push(searchLat, searchLng);
localStorage.setItem("lat, Long", searchedLoc);

**Comment by rmwillow** [comment]
it will not work if it is placed before the declared variables

**Comment by rmwillow** [comment]
// Store

//create a list to store lat and long in
let searchedLoc = [];

//push lat and long variables into list
searchedLoc.push(searchLat, searchLng);

//store list in local storage with the name of lat, long
localStorage.setItem("lat, Long", searchedLoc);
